#!/usr/bin/env bash
# Description: Hot-swaps Nginx upstream configurations and reloads cleanly.
set -euo pipefail

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Read port environment file generated by the allocator
ENV_FILE="/tmp/gigflow_next_target.env"
if [[ ! -f "$ENV_FILE" ]]; then
    echo -e "${RED}[!] Target environment variables missing. Run port allocator first.${NC}"
    exit 1
fi

source "$ENV_FILE"
echo -e "${YELLOW}[*] Rerouting live production traffic to port: ${TARGET_PORT}...${NC}"

# Define the Nginx config snippet that holds the variable proxy port
NGINX_UPSTREAM_CONF="/etc/nginx/conf.d/gigflow_upstream.conf"

# Generate the isolated upstream configuration
# Note: Requires sudo permissions on the host system
echo "upstream gigflow_backend { server 127.0.0.1:${TARGET_PORT}; }" | sudo tee "$NGINX_UPSTREAM_CONF" > /dev/null

# Hot-reload Nginx gracefully without breaking active connections
if sudo nginx -t && sudo systemctl reload nginx; then
    echo -e "${GREEN}[*] Traffic hot-swap complete. Live connections seamlessly routed.${NC}"
else
    echo -e "${RED}[!] Nginx configuration verification failed. Reverting changes.${NC}"
    exit 1
fi
